using System;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.UI;



public class EnglishLogic : MonoBehaviour
{
    public TMP_Dropdown tenseDropdown;
    public TMP_Dropdown phraseTypeDropdown;

    [SerializeField] GameObject rememberPanel;

    public TMP_InputField userInputField;
    public Button checkButton;
    public TMP_Text feedbackText;
    public TMP_Text rule_dynamic_text;
    public string selectedTense = ""; // Cambia a seconda dell'esercizio

    // Fare HelpMe Button che mostra una delle frasi dopo la pubblicità

    HashSet<string> present_simple_affirmations = new HashSet<string>(StringComparer.OrdinalIgnoreCase){
         "She always eats breakfast in the morning",
        "They sometimes play football on Sundays",
        "He often studies late at night",
        "We rarely watch TV during the week",
        "You never forget your keys",
        "It usually rains in November",
        "I hardly ever drink coffee",
        "She occasionally goes to the gym after work",
        "He quickly finishes his homework",
        "We quietly enter the room to avoid disturbing others",
        "They eagerly wait for the holidays every year",
        "You easily solve math problems",
        "She regularly checks her email in the morning",
        "He slowly walks to school when he feels tired",
        "They happily help their neighbors with gardening",
        "We frequently visit the library on weekends",
        "I seldom eat fast food",
        "He boldly speaks in front of large audiences",
        "She carefully drives on icy roads",
        "You always arrive on time",
        "She is always helping her friends with homework.",
        "They are often playing outside in the garden",
        "He is usually talking to his friends after school",
        "We are constantly working on improving our skills",
        "She is rarely cooking dinner for herself",
        "They are happily discussing the upcoming event",
        "He is slowly learning how to play the guitar",
        "She is completely understanding the lesson now",
        "We are frequently meeting at the cafe to talk",
        "He is hardly ever missing his appointments",
        "They are currently preparing for the big match",
        "She is quickly finishing her presentation",
        "We are patiently waiting for the train to arrive",
        "He is rarely arguing with his brother these days",
        "She is never forgetting to bring her umbrella",
        "They are quietly sitting in the library at the moment",
        "We are regularly exercising to stay fit"
    };
    
    HashSet<string> present_simple_questions = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
    {
        "What have you done today?",
        "Will she come to the meeting?",
        "What will you do tomorrow?",
        "Was he sleeping at that time?",
        "What were you doing yesterday evening?",
        "Why did he leave early?",
        "What did you do yesterday?",
        "How is she working today?",
        "What are you doing?",
        "How often do you visit your parents?",
        "does she like pizza?",
        "does she drink coffee?",
        "do they visit their grandparents?",
        "does he drive a car?",
        "do you enjoy music?",
        "does it rain often?",
        "do we arrive on time?",
        "does john play the piano?",
        "do the students listen to the teacher?",
        "does her brother work in an office?",
        "do my parents call me every day?",
        "does sarah write emails?",
        "do they like ice cream?",
        "does he walk to work?",
        "do you cook dinner?",
        "does it cost a lot?",
        "do we watch movies?",
        "does david travel often?",
        "do the kids do their homework?",
        "does your cat sleep a lot?",
        "do my neighbors have a car?",
        "does she clean the house?",
        "do they visit the museum?",
        "does he buy new clothes?",
        "do you sell books?",
        "does it work correctly?",
        "do we exercise daily?",
        "does emma dance well?",
        "do the birds sing in the morning?",
        "does his father fix cars?",
        "do my friends like sushi?",
        "does alice bake cakes?",
        "do they enjoy swimming?",
        "does he watch youtube?",
        "do you play chess?",
        "does it smell bad?",
        "do we take the bus?",
        "does tom paint pictures?",
        "do the workers arrive early?",
        "does her mother call her every day?",
        "do my cousins live in france?",
        "does she eat vegetables?",
        "do they study hard?",
        "does he read newspapers?",
        "do you prefer tea?",
        "does it sound good?",
        "do we sleep well?",
        "does jack help his brother?",
        "do the dogs bark at night?",
        "does his uncle work in a shop?",
        "do my classmates like math?",
        "does lily go to the gym?",
        "do they ride bicycles?",
        "does he repair computers?",
        "do you send emails?",
        "does it taste sweet?",
        "do we finish work at six?",
        "does sam play soccer?",
        "do the tourists visit london?",
        "does her boyfriend buy gifts?",
        "do my teachers give homework?",
        "does she open the windows?",
        "do they order food online?",
        "does he watch the news?",
        "do you wear a hat?",
        "does it rain in winter?",
        "do we dance at parties?",
        "does mike play video games?",
        "do the engineers build bridges?",
        "does his cousin study medicine?",
        "do my parents wake up early?",
        "does she brush her teeth?",
        "do they visit the zoo?",
        "does he love pizza?",
        "do you drink water?",
        "does it shine in summer?",
        "do we work together?",
        "does lisa wear glasses?",
        "do the children play outside?",
        "does her sister drive fast?",
        "do my grandparents travel a lot?",
        "does she listen to the radio?",
        "do they cook breakfast?",
        "does he teach english?",
        "do you like rock music?",
        "does it freeze in winter?",
        "do we meet on fridays?",
        "does james fix bikes?",
        "do the nurses take care of patients?",
        "does his boss arrive late?",
        "Why does she always drink coffee in the morning?",
        "When do they usually visit their grandparents on weekends?",
        "Where does he drive his car every evening?",
        "How often do you enjoy live music at the concert hall?",
        "Why does it rain so much in this city?",
        "What time do we normally arrive at the office?",
        "Which instrument does John play at the music academy?",
        "How do the students listen carefully to the teacher's explanations?",
        "Where does her brother work as an accountant in the city?",
        "Why do my parents always call me before dinner?",
        "When does Sarah write emails to her colleagues?",
        "Why do they love eating ice cream in winter?",
        "How far does he walk to work every morning?",
        "What dish do you usually cook for dinner?",
        "How much does it cost to park here for an hour?",
        "Why do we always watch horror movies at night?",
        "How frequently does David travel abroad for business?",
        "When do the kids do their homework after school?",
        "Where does your cat sleep during the day?",
        "Why do my neighbors always complain about the noise?",
        "How does she clean the house so quickly?",
        "Why do they visit the museum every Sunday?",
        "How often does he buy new clothes for special occasions?",
        "What kind of books do you usually sell at the store?",
        "Why does it work better with a new battery?",
        "How many hours do we exercise every week?",
        "Why does Emma dance so well at competitions?",
        "When do the birds start singing in the morning?",
        "How does his father fix cars so efficiently?",
        "Why do my friends love eating sushi at that restaurant?",
        "What type of cakes does Alice bake for birthdays?",
        "How much do they enjoy swimming in the lake?",
        "When does he watch YouTube after work?",
        "Why do you always play chess with your grandfather?",
        "How bad does it smell in the garbage room?",
        "What bus do we take to get to the museum?",
        "How does Tom paint such realistic pictures?",
        "When do the workers usually arrive at the factory?",
        "Why does her mother call her three times a day?",
        "How often do my cousins visit France for vacations?",
        "What vegetables does she eat for lunch?",
        "How long do they study for their exams?",
        "When does he read newspapers in the morning?",
        "Why do you prefer tea over coffee?",
        "How well does it sound with the new speakers?",
        "What time do we usually sleep on weekends?",
        "How often does Jack help his brother with homework?",
        "Why do the dogs bark at night so loudly?",
        "Where does his uncle work as a shop assistant?",
        "How much do my classmates like studying math?",
        "Why does Lily go to the gym so early?",
        "When do they ride bicycles in the park?",
        "How does he repair computers so quickly?",
        "Why do you send emails instead of calling?",
        "How sweet does it taste with honey?",
        "What time do we finish work on Fridays?",
        "How well does Sam play soccer?",
        "When do the tourists visit London the most?",
        "Why does her boyfriend buy expensive gifts?",
        "How much homework do my teachers give every day?",
        "How many windows does she open in the house?",
        "Why do they order food online instead of cooking?",
        "When does he watch the news on TV?",
        "Why do you wear a hat in summer?",
        "How much does it rain in winter?",
        "What kind of music do we dance to at parties?",
        "How often does Mike play video games?",
        "When do the engineers build new bridges?",
        "Why does his cousin study medicine abroad?",
        "How early do my parents wake up in the morning?",
        "Does she often visit her grandparents?",
        "Do you always drink coffee in the morning?",
        "Does she sometimes go to the park?",
        "Do they often play soccer after school?",
        "Does he rarely visit his grandparents?",
        "Do we never forget our appointments?",
        "Do you sing loudly in the shower?",
        "Does she write carefully when sending emails?",
        "Do they speak fluently in English?",
        "Does he read quietly at the library?",
        "Do we work efficiently during the day?",
        "Do you call your friends every evening?",
        "Does he visit his grandmother on Sundays?",
        "Do they study hard before exams?",
        "Does she arrive early every morning?",
        "Do we meet after work on Fridays?",
        "Do you live here in the city?",
        "Does she work there at the office?",
        "Do they play outside when it’s sunny?",
        "Does he stay indoors during winter?",
        "Do we go somewhere special for vacations?",
        "Do you really like this movie?",
        "Does she completely understand the rules?",
        "Do they fully agree with the decision?",
        "Does he hardly finish his tasks on time?",
        "Do we almost miss the bus every day?",
        "How often do you exercise?",
        "Why does he always arrive late?",
        "When do we usually have meetings?",
        "Where do they practice basketball?",
        "What time does she usually wake up?"
    };
    HashSet<string> present_continuous_questions = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
    {
        "What are you doing?", "Is she working today?", "Are they coming to the meeting?",
        "Why is he laughing?", "Are we going to the cinema tonight?", "What are you thinking about?",
        "Is it raining outside?", "Are you studying English now?", "Who is calling me at this moment?",
        "Are they staying at a hotel?", "Is she cooking dinner tonight?", "Where are you going?",
        "Is he playing the piano right now?", "Why are you shouting?", "Are we waiting for the bus?",
        "Is she reading a book or watching TV?", "Are you working on the project?", "What are they discussing?",
        "Are you having fun?", "Who is running in the park?", "Is the dog barking outside?",
        "Why are they arguing again?", "Is he singing a song?", "What are you eating for lunch?",
        "Is she painting a picture?", "Where are they traveling to?", "Are we meeting him tomorrow?",
        "Why is it snowing in April?", "Are you talking to your friend?", "Is she shopping now?",
        "Who is helping you?", "Are they learning something new?", "Is he swimming at the moment?",
        "Are you feeling okay?", "Why is she crying?", "Are we going together?", "What are they watching?",
        "Is he walking to school?", "Where are you sitting?", "Is she doing yoga this morning?",
        "Are you writing a letter?", "Why is the cat sleeping on the bed?", "Are they enjoying the party?",
        "What are you planning for the weekend?", "Is he fixing his car?", "Are we taking the right road?",
        "Is she practicing her dance routine?", "Where are they moving to?", "Who is joining us for dinner?",
        "Are you dancing to this song?", "Why are they cleaning the house?", "Is it becoming colder?",
        "What are you waiting for?", "Is she designing a new outfit?", "Are they searching for something?",
        "Are you washing the dishes?", "Why is she speaking so loudly?", "What are you learning?",
        "Is he organizing the files?", "Are we starting the meeting soon?", "Who is visiting you today?",
        "Are you checking your email?", "Is she preparing a presentation?", "Why are they standing there?",
        "Are we trying a new recipe?", "What are they building in the garden?", "Is he exploring the city?",
        "Are you enjoying the vacation?", "Why is the baby crying?", "Is she feeding the birds?",
        "What are they repairing?", "Is it getting dark outside?", "Are you making a cake?",
        "Why is she smiling?", "What are we forgetting?", "Is he opening the store?", "Are you calling your mom?",
        "Where are you driving?", "Are they recording the video?", "Is she solving a puzzle?",
        "Why are they sitting there?", "Are we improving our skills?", "What is he playing?",
        "Are you fixing the chair?", "Why is he holding the book?", "Is she delivering a speech?",
        "What are you organizing?", "Is it working as expected?", "Are we heading home?",
        "Why are they celebrating?", "What are you waiting for?", "Is she talking to her teacher?",
        "Where are they parking the car?", "Is he buying groceries?", "Are we leaving soon?",
        "Who is calling at this hour?", "Are they discussing the news?",
        "What are you doing right now?",
        "Is she working on her project?",
        "Are they coming to the party tonight?",
        "Why is he laughing so much?",
        "Are we going to the park this afternoon?",
        "What is it raining for all day?",
        "Are you studying for your exam?",
        "Who is calling you at this moment?",
        "Are they staying at their aunt's house?",
        "Is she cooking dinner for everyone?",
        "Where are you heading to?",
        "Is he playing the guitar right now?",
        "Why are you shouting so loudly?",
        "Are we waiting for the bus here?",
        "Is she reading that new book?",
        "Are you writing an email to your teacher?",
        "What are they discussing during the meeting?",
        "Is the dog barking at the neighbors again?",
        "Why are they arguing this time?",
        "Is he singing that new song?",
        "What are you eating for lunch today?",
        "Is she painting another landscape?",
        "Where are they moving next month?",
        "Are we meeting our friends later?",
        "Why is it snowing in spring?",
        "Are you talking to the new colleague?",
        "Is she shopping for groceries now?",
        "Who is helping you set up the tent?",
        "Are they learning anything useful?",
        "Is he swimming in the cold lake?",
        "Are you feeling better now?",
        "Why is she crying all of a sudden?",
        "Are we going out for dinner tonight?",
        "What are they watching on TV?",
        "Is he walking the dog in the park?",
        "Where are you sitting in the classroom?",
        "Is she doing yoga at this hour?",
        "Are you making a chocolate cake?",
        "Why is the cat sleeping on the couch?",
        "Are they dancing to this song?",
        "Is it becoming colder outside?",
        "What are you planning for the weekend?",
        "Is she designing new clothes for the show?",
        "Are they cleaning the kitchen together?",
        "Are you washing the car this afternoon?",
        "Why is he holding the umbrella inside?",
        "What are you organizing for the party?",
        "Are they recording a new album?",
        "Is he solving that complicated puzzle?",
        "Are we improving our skills at practice?",
        "Why are they celebrating so loudly?",
        "Are you calling your parents tonight?",
        "Is she delivering an important speech tomorrow?",
        "What are they building in their backyard?",
        "Are we starting the project this week?",
        "Is it working as intended?",
        "Are you enjoying the concert so far?",
        "Why are they sitting in the corner?",
        "Who is joining us for dinner tonight?",
        "Where are they parking the car?",
        "Why is she laughing uncontrollably?",
        "Are you checking your messages now?",
        "What is he playing on the piano?",
        "Are you fixing the broken chair?",
        "Is she feeding the birds in the garden?",
        "Are they taking pictures of the sunset?",
        "Are we heading home soon?",
        "Why is the baby crying?",
        "Are you exploring the new city center?",
        "Is he dancing at the party right now?",
        "Where are you going this evening?",
        "Why is she looking at him like that?",
        "Is he opening the store in the morning?",
        "Are you following the instructions carefully?",
        "What are you waiting for?",
        "Is she talking to the manager?",
        "Why are they learning Spanish?",
        "Is he reading the newspaper outside?",
        "Are you staying for lunch?",
        "Where are they playing football?",
        "Why is it getting dark already?",
        "Are you drawing something interesting?",
        "Is she trying on the new dress?",
        "Are they working from home today?",
        "Is he writing a novel at the moment?",
        "What are you listening to?",
        "Are you packing for the trip tomorrow?",
        "Why are they leaving so early?",
        "Is he playing video games again?",
        "What are you looking for in the drawer?",
        "Is she solving the math problems?",
        "Where are you traveling next summer?",
        "Why are they speaking so softly?",
        "Are you helping your friend move?",
        "Is the teacher explaining the lesson now?",
        "Are we preparing for the exam together?",
        "Why are you always laughing so loudly?",
        "Is she really enjoying her vacation now?",
        "Are they studying at home tonight?",
        "What are we doing quickly to solve this problem?",
        "Where are you sitting here during the class?",
        "Are you always helping your friends with their homework?",
        "Is he often working late at the office?",
        "Are they really enjoying the party?",
        "Is she usually talking to her neighbors in the evening?",
        "Are we constantly improving our skills during these sessions?",
        "Is she rarely cooking dinner for herself these days?",
        "Are they happily planning their next holiday?",
        "Is he slowly learning how to play the piano?",
        "Are you carefully writing down the instructions?",
        "Is she completely understanding the new lesson?",
        "Are we frequently meeting at the library after class?",
        "Are they hardly ever missing these important meetings?",
        "Are you currently preparing for your trip abroad?",
        "Is she quickly finishing her assignment now?",
        "Are we patiently waiting for the train to arrive?",
        "Are they always cleaning the kitchen together?",
        "Is he rarely arguing with his siblings lately?",
        "Is she never forgetting to bring her notebook?",
        "Are they quietly sitting in the living room right now?",
        "Are we regularly exercising to stay in shape?"
};
    HashSet<string> past_simple_questions = new HashSet<string>(StringComparer.OrdinalIgnoreCase) {
        "Did she always arrive on time?",
        "Did they often play soccer after school?",
        "Did he usually walk to work?",
        "Did we never forget to call our parents?",
        "Did you sometimes visit your grandparents?",
        "Did he rarely miss his appointments?",
        "Did she occasionally cook dinner for her friends?",
        "Did they frequently travel abroad?",
        "Did you ever try to solve that puzzle?",
        "Did we regularly attend meetings at the office?",
        "Did he speak clearly during the presentation?",
        "Did she write carefully in her notebook?",
        "Did they work efficiently on the project?",
        "Did you drive slowly on the icy roads?",
        "Did we explain everything thoroughly?",
        "Did he finish the task quickly?",
        "Did she smile brightly when she saw you?",
        "Did they respond politely to the teacher?",
        "Did you behave well at the party?",
        "Did we act responsibly during the event?",
        "Did she call you yesterday?",
        "Did they leave early this morning?",
        "Did he return home last night?",
        "Did you visit the museum last weekend?",
        "Did we attend the concert last month?",
        "Did she arrive late on Monday?",
        "Did they finish their homework on time?",
        "Did he speak to you earlier today?",
        "Did you see her at the event yesterday evening?",
        "Did we meet them last Friday?",
        "Did you stay here during the holidays?",
        "Did she work there for a year?",
        "Did they travel abroad for the conference?",
        "Did he sit outside in the garden?",
        "Did we meet at the cafe last week?",
        "Did you park the car nearby?",
        "Did she study at home before the exam?",
        "Did they walk along the river yesterday?",
        "Did he stay in Italy during the summer?",
        "Did we play basketball at school?",
        "Did she visit her grandparents?",
        "Did they enjoy the party?",
        "Did he fix the car?",
        "Did you buy a new book?",
        "Did we win the game?",
        "Did she tell you the truth?",
        "Did they help you with the homework?",
        "Did he go to the park?",
        "Did you eat lunch at the restaurant?",
        "Did we watch the movie together?",
        "Did she clean the house yesterday?",
        "Did they study for the exam?",
        "Did he drive to work?",
        "Did you call your friend?",
        "Did we start the project on time?",
        "What did she say during the meeting?",
        "Where did they go after the event?",
        "Why did he leave early?",
        "When did you meet her?",
        "How did we solve the problem?",
        "Which book did she choose from the library?",
        "Who did he call last night?",
        "What time did you arrive at the station?",
        "Why did they cancel the trip?",
        "Where did we stay during the vacation?",
        "Did you finish the assignment on time?",
        "Did he apologize for his mistake?",
        "Did she bake a cake for the party?",
        "Did they find the missing keys?",
        "Did you call your parents yesterday?",
        "Did we enjoy the concert last night?",
        "Did she attend the wedding?",
        "Did he forget to bring his notebook?",
        "Did they win the competition?",
        "Did you lock the door before leaving?",
        "Did we decide on the meeting schedule?",
        "Did she lend you her book?",
        "Did he hurt himself during the game?",
        "Did they arrive before the deadline?",
        "Did you buy groceries at the store?",
        "Did we plan the vacation in advance?",
        "Did she work late last night?",
        "Did he prepare for the presentation?",
        "Did they wait long for the bus?",
        "Did you speak to the manager?",
        "Did we help the team with their project?",
        "Did she call her friend after class?",
        "Did they visit the museum in the afternoon?",
        "Did you ask the teacher for help?",
        "Did he eat the last slice of pizza?",
        "Did she read the email carefully?",
        "Did they organize the event properly?",
        "Did you join the discussion group?",
        "Did we explore the city yesterday?",
        "Did she perform well in the play?",
        "Did he explain the topic in detail?",
        "Did they take notes during the lecture?",
        "Did you stay at the hotel last weekend?",
        "Did we miss the train in the morning?",
        "Did she paint the walls in the living room?",
        "Did he learn a new language last year?",
        "Did they play music at the party?",
        "Did you find the answer to the question?",
        "Did we celebrate the occasion together?",
        "Did she buy tickets for the movie?",
        "Did he forget the appointment time?",
        "Did they enjoy the meal at the restaurant?",
        "Did you invite them to the wedding?",
        "Did we complete the project on schedule?",
        "Did she dance at the party last night?",
        "Did he sleep well after the long trip?",
        "Did they hike in the mountains during the vacation?",
        "Did you attend the workshop on Saturday?",
        "Did we discuss the topic in the meeting?",
        "Did she bring the flowers for the table?",
        "Did he clean the car yesterday?",
        "Did they solve the puzzle before dinner?",
        "Did you pack your bags for the trip?",
        "Did we start the new chapter in class?",
        "Did she accept the job offer?",
        "Did he apologize for his behavior?",
        "Did they repair the broken window?",
        "Did you hear the news about the event?",
        "Did we watch the sunrise on the beach?",
        "Did she recommend a good restaurant?",
        "Did he cancel the appointment?",
        "Did they water the plants in the garden?",
        "Did you borrow a book from the library?",
        "Did we check the weather forecast?",
        "Did she attend the yoga class?",
        "Did he complete the marathon?",
        "Did they participate in the contest?",
        "Did you enjoy the view from the hill?",
        "Did we travel to the countryside last weekend?",
        "Did she fix the clock in the kitchen?",
        "Did he win the chess tournament?",
        "Did they paint the fence last week?",
        "Did you lose your keys at the park?",
        "Did we return the rented car?",
        "Did she organize the files on her desk?",
        "Did he eat dessert after dinner?",
        "Did they build a sandcastle on the beach?",
        "Did you visit the doctor yesterday?",
        "Did we arrive early for the meeting?",
        "Did she help her neighbor with the groceries?",
        "Did he open the store early in the morning?",
        "Did they attend the art exhibition?",
        "Did you enjoy the music at the concert?",
        "Did we prepare the meal together?",
        "Did she answer the phone call?",
        "Did he lose his wallet at the station?",
        "Did they drive to the countryside?",
        "Did you explain the rules of the game?",
        "Did we organize the team for the competition?",
        "Did she find the solution to the problem?",
        "Did he watch the documentary on TV?",
        "Did they practice for the final match?",
        "Did you meet him at the cafe yesterday?",
        "Did we hear the announcement at the station?",
        "Did she deliver the package on time?",
        "Did he repair the old radio?",
        "Did they order pizza for dinner?",
        "Did you complete the homework before class?",
        "Did we celebrate the anniversary together?"

    };
    HashSet<string> past_continuous_questions = new HashSet<string>(StringComparer.OrdinalIgnoreCase) {
        "Was she always helping her friends with their homework?",
        "Were they often playing soccer after school?",
        "Was he usually walking to the park?",
        "Were we constantly working on the project?",
        "Was she rarely cooking dinner for herself?",
        "Were they frequently traveling to new places?",
        "Were you ever trying to finish that book?",
        "Was he quietly reading in the library?",
        "Were they happily planning the trip together?",
        "Was she speaking loudly during the meeting?",
        "Were we carefully analyzing the data?",
        "Was he quickly solving the problem?",
        "Were they regularly attending the workshops?",
        "Was she fluently speaking in Spanish?",
        "Were you slowly completing the task?",
        "Were we patiently waiting for the train to arrive?",
        "Was she dancing gracefully at the party?",
        "Was he silently writing in his notebook?",
        "Were they consistently improving their performance?",
        "Was she always thinking about her future?",
        "Were you studying for the test yesterday evening?",
        "Was he calling you several times yesterday?",
        "Were they driving to the countryside in the afternoon?",
        "Was she cleaning the house when the guests arrived?",
        "Were we preparing for the big event all day?",
        "Were you checking your emails while waiting?",
        "Was he organizing his desk when you saw him?",
        "Was she cooking dinner when the lights went out?",
        "Were they watching TV at the same time?",
        "Was he explaining the concept during the lecture?",
        "Were you listening to music while working?",
        "Was she painting the wall in her room?",
        "Were they running in the park when it started raining?",
        "Was he always behaving well during class?",
        "Were you playing the piano when I arrived?",
        "Was she waiting for the bus in the morning?",
        "Were we thinking about our next steps?",
        "Were they walking along the beach at sunset?",
        "Were you eating breakfast when the phone rang?",
        "Was he fixing the car when the storm started?",
        "Were they smiling when you saw them?",
        "Was she enjoying the concert yesterday?",
        "Were we taking notes during the presentation?",
        "Was he singing that new song at the event?",
        "Were they working on their project together?",
        "Was she shopping for groceries in the market?",
        "Were you having lunch at the cafe yesterday?",
        "Was he drawing a picture in his sketchbook?",
        "Were they helping their neighbors move furniture?",
        "Were we making plans for the weekend last night?",
        "Was she walking her dog in the evening?",
        "Was he studying at the library yesterday?",
        "Were they performing on stage during the festival?",
        "Were you organizing the files when I entered?",
        "Was she feeding the cats when it started raining?",
        "Was he repairing his bike in the garage?",
        "Were they cooking dinner for the guests?",
        "Was she dancing with her partner at the wedding?",
        "Were we practicing for the competition all day?",
        "Was he driving to the airport when you called?",
        "Were they teaching a new lesson yesterday?",
        "Was she visiting her grandmother last Sunday?",
        "Were you playing chess with your brother?",
        "Was he sitting near the fireplace during winter?",
        "Were they swimming in the lake in the afternoon?",
        "Were we preparing the room for the event?",
        "Was she reading a novel in her free time?",
        "Were you waiting for the bus when it broke down?",
        "Was he eating at the restaurant last night?",
        "Were they exploring the city during their trip?",
        "Was she decorating the house for the party?",
        "Were we reviewing our notes before the test?",
        "Was he walking to school in the morning?",
        "Were they solving a puzzle at the kitchen table?",
        "Was she driving when the accident happened?",
        "Were you finishing your homework before dinner?",
        "Was he looking for his lost keys in the morning?",
        "Were they discussing the plan during the meeting?",
        "Was she organizing the documents at the office?",
        "Were you drawing a sketch in your notepad?",
        "Was he delivering packages for his job?",
        "Were they playing outside while it was raining?",
        "Was she helping her mother with cooking?",
        "Were you speaking to the manager yesterday?",
        "Was he focusing on his work when we interrupted?",
        "Were we shopping for clothes at the mall?",
        "Was she practicing yoga in the garden?",
        "Were they building a sandcastle on the beach?",
        "Was he cleaning his glasses while talking?",
        "Were you eating lunch during the break?",
        "Was she planning her next vacation last night?",
        "Were they cleaning their room all morning?",
        "Was he listening to the radio while driving?",
        "Were we searching for the lost item together?",
        "Was she making coffee when the guests arrived?",
        "Were you watching a movie when I called?",
        "Was he talking to the teacher after class?",
        "Were they riding their bikes in the park?",
        "Was she crying during the emotional scene?",
        "Were we heading to the station in the evening?",
        "Were you exercising at the gym yesterday?",
        "Was he painting his house last weekend?",
        "Were they holding hands while crossing the street?",
        "Were you preparing a presentation for the meeting?",
        "Was she playing cards with her friends yesterday?",
        "Were we sailing on the lake in the afternoon?",
        "Was he ironing his clothes in the morning?",
        "Were they sweeping the floor when you arrived?",
        "Was she baking cookies for her children?",
        "Were you reading a magazine in the waiting room?",
        "Was he designing a website for his client?",
        "Were they talking about their project last night?",
        "Were we planting trees in the garden yesterday?",
        "Was she solving math problems before dinner?",
        "Were you brushing your teeth before bed?",
        "Was he carrying the heavy boxes upstairs?",
        "Were they practicing their dance routine on stage?",
        "Was she arranging flowers in the vase?",
        "Were you learning a new recipe while cooking?",
        "Was he trying to fix the broken chair?",
        "Were they waiting for their friends in the park?",
        "Was she swimming in the pool when it started raining?",
        "Were we climbing the mountain in the morning?",
        "Was he editing a video on his computer?",
        "Were you feeding the birds in the backyard?",
        "Was she singing her favorite song in the shower?",
        "Were they jogging along the river yesterday?",
        "Was he sharpening his pencils for drawing?",
        "Were we exploring the cave during our trip?",
        "Was she tasting the soup while cooking?",
        "Were you organizing the party decorations?",
        "Was he answering emails while in the office?",
        "Were they carrying groceries from the market?",
        "Was she attending a workshop in the afternoon?",
        "Were you writing your journal last night?",
        "Was he whispering during the conversation?",
        "Were they relaxing on the couch after lunch?",
        "Was she dusting the furniture in the living room?",
        "Were we laughing at the joke he told?",
        "Was he wiping the windows of the car?",
        "Were you sewing your dress for the event?",
        "Was she dreaming about the future while sleeping?",
        "Were they learning to play the violin yesterday?",
        "Was he knitting a scarf for the winter?",
        "Were you polishing the silverware for dinner?",
        "Was she designing the layout for the book?",
        "Were we climbing the hill under the sunset?",
        "Were they whispering secrets to each other?",
        "Was he calculating the expenses in the morning?"
    };
    HashSet<string> future_simple_questions = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
    {
        "Will she always help her friends with their homework?",
        "Will they often play soccer after school?",
        "Will he usually walk to the park?",
        "Will we constantly work on this project?",
        "Will you rarely cook dinner for yourself?",
        "Will they frequently travel to new cities?",
        "Will she ever try to finish that book?",
        "Will he quietly read in the library tomorrow?",
        "Will they happily plan the trip together next weekend?",
        "Will she speak loudly during the presentation?",
        "Will we carefully analyze the data tomorrow?",
        "Will he quickly solve the problem?",
        "Will they regularly attend the workshops?",
        "Will you slowly complete the task today?",
        "Will we patiently wait for the train to arrive?",
        "Will she dance gracefully at the party?",
        "Will he silently write in his notebook tonight?",
        "Will they consistently improve their performance?",
        "Will she always think about her goals?",
        "Will you study for the test tomorrow evening?",
        "Will he call you several times next week?",
        "Will they drive to the countryside in the afternoon?",
        "Will she clean the house before the guests arrive?",
        "Will we prepare for the big event next Monday?",
        "Will you check your emails in the morning?",
        "Will he organize his files next week?",
        "Will she cook dinner when you visit?",
        "Will they watch the show together tonight?",
        "Will he explain the project during the meeting?",
        "Will you listen to music while working tomorrow?",
        "Will she paint the wall in her new room?",
        "Will they run in the park tomorrow morning?",
        "Will he always behave well during class?",
        "Will you play the piano when I arrive?",
        "Will she wait for the bus in the morning?",
        "Will we think about the future next year?",
        "Will they walk along the beach at sunset?",
        "Will you eat breakfast before the meeting?",
        "Will he fix the car before the weekend?",
        "Will they smile when they see you?",
        "Will she enjoy the concert tomorrow evening?",
        "Will we take notes during the session?",
        "Will he sing the new song at the event?",
        "Will they work together on the presentation?",
        "Will she shop for groceries tomorrow?",
        "Will you have lunch at the cafe with us?",
        "Will he draw a picture in his sketchbook?",
        "Will they help their neighbors move furniture?",
        "Will we make plans for the weekend tonight?",
        "Will she walk her dog in the evening?",
        "Will he study at the library tomorrow?",
        "Will they perform on stage during the festival?",
        "Will you organize the documents next week?",
        "Will she feed the cats before leaving?",
        "Will he repair his bike next weekend?",
        "Will they cook dinner for the guests tomorrow?",
        "Will she dance at the wedding reception?",
        "Will we practice for the competition on Saturday?",
        "Will he drive to the airport in the morning?",
        "Will they teach the new lesson tomorrow?",
        "Will she visit her grandmother next Sunday?",
        "Will you play chess with your brother?",
        "Will he sit near the fireplace during winter?",
        "Will they swim in the pool tomorrow afternoon?",
        "Will we prepare the room for the event later?",
        "Will she read a novel in her spare time?",
        "Will you wait for the bus at the corner?",
        "Will he eat at the new restaurant next week?",
        "Will they explore the city during their trip?",
        "Will she decorate the house for the holidays?",
        "Will we review our notes before the test?",
        "Will he walk to school in the morning?",
        "Will they solve the puzzle in time?",
        "Will she drive when the car is ready?",
        "Will you finish your homework before dinner?",
        "Will he look for his keys in the morning?",
        "Will they discuss the plan during the meeting?",
        "Will she organize her desk this week?",
        "Will you draw a sketch in your notebook?",
        "Will he deliver the package this evening?",
        "Will they play outside while it’s sunny?",
        "Will she help her mother with cooking?",
        "Will you speak to the manager tomorrow?",
        "Will he focus on his work this afternoon?",
        "Will we shop for new clothes this weekend?",
        "Will she practice yoga in the garden tomorrow?",
        "Will they build a sandcastle on the beach?",
        "Will he clean his glasses during the break?",
        "Will you eat lunch with us later?",
        "Will she plan her next vacation tonight?",
        "Will they clean their rooms before lunch?",
        "Will he listen to the radio while driving?",
        "Will we search for the missing items later?",
        "Will she make coffee for everyone?",
        "Will you watch a movie in the evening?",
        "Will he talk to the teacher after school?",
        "Will they ride their bikes to the park?",
        "Will she cry during the emotional movie?",
        "Will we head to the station together?",
        "Will you exercise at the gym tomorrow?",
        "Will he paint his house over the weekend?",
        "Will they hold hands while crossing the street?",
        "Will you prepare your presentation for tomorrow?",
        "Will she play cards with her friends later?",
        "Will we sail on the lake during our trip?",
        "Will he iron his clothes in the morning?",
        "Will they sweep the floor after breakfast?",
        "Will she bake cookies for the party?",
        "Will you read a book before bed?",
        "Will he design a new website for his client?",
        "Will they talk about their plans for the future?",
        "Will we plant flowers in the garden this weekend?",
        "Will she solve math problems for practice?",
        "Will you brush your teeth before sleeping?",
        "Will he carry the heavy boxes to the attic?",
        "Will they practice their dance routine later?",
        "Will she arrange flowers in the vase?",
        "Will you learn to cook a new dish?",
        "Will he try to fix the broken chair?",
        "Will they wait for their friends at the park?",
        "Will she swim in the pool this afternoon?",
        "Will we climb the mountain tomorrow?",
        "Will he edit the video on his laptop?",
        "Will you feed the birds in the backyard?",
        "Will she sing her favorite song at the event?",
        "Will they jog along the river tomorrow?",
        "Will he sharpen his pencils for the project?",
        "Will we explore the cave during our trip?",
        "Will she taste the soup before serving?",
        "Will you organize the party decorations?",
        "Will he answer emails before the meeting?",
        "Will they carry groceries from the store?",
        "Will she attend the workshop next week?",
        "Will you write in your journal before sleeping?",
        "Will he whisper during the conversation?",
        "Will they relax on the couch after dinner?",
        "Will she dust the furniture tomorrow morning?",
        "Will we laugh at the joke he tells?",
        "Will he wipe the windows of the car tomorrow?",
        "Will you sew your dress for the event?",
        "Will she dream about her future tonight?",
        "Will they learn to play the piano soon?",
        "Will he knit a scarf for winter?",
        "Will you polish the silverware before dinner?",
        "Will she design the cover for her book?",
        "Will we climb the hill in the evening?",
        "Will they whisper secrets to each other?",
        "Will he calculate the budget for the trip?"

    };
    HashSet<string> present_perfect_questions = new HashSet<string>(StringComparer.OrdinalIgnoreCase) {
        "Have you ever traveled abroad?",
        "Has she already finished her homework?",
        "Have they always lived in this house?",
        "Have we just completed the project?",
        "Has he ever played the piano?",
        "Have you often visited your grandparents?",
        "Has she finally solved the problem?",
        "Have they frequently gone hiking in the mountains?",
        "Have you already eaten lunch?",
        "Has he recently joined the team?",
        "Have we always worked together?",
        "Has she ever written a novel?",
        "Have they already started the meeting?",
        "Have you never missed a deadline?",
        "Has he often helped his classmates?",
        "Have we recently spoken to the manager?",
        "Have you ever sung in public?",
        "Has she just arrived at the office?",
        "Have they always enjoyed classical music?",
        "Have you often practiced yoga?",
        "Has he already completed the assignment?",
        "Have we recently cleaned the house?",
        "Have you ever driven a sports car?",
        "Has she frequently visited the art gallery?",
        "Have they just left the building?",
        "Have you always believed in yourself?",
        "Has he already called his parents?",
        "Have we recently discussed this topic?",
        "Have you ever participated in a marathon?",
        "Has she often read historical novels?",
        "Have they just submitted their application?",
        "Have you already prepared your speech?",
        "Has he always admired his teacher?",
        "Have we ever worked late at night?",
        "Have you ever forgotten something important?",
        "Has she recently moved to a new city?",
        "Have they always been supportive?",
        "Have you just checked your emails?",
        "Has he ever painted a portrait?",
        "Have we frequently visited this museum?",
        "Have you already finished your breakfast?",
        "Has she ever been to Paris?",
        "Have they often argued about politics?",
        "Have you recently met with the director?",
        "Has he always been an early riser?",
        "Have we just booked the tickets?",
        "Have you ever climbed a mountain?",
        "Has she often traveled for work?",
        "Have they already cleaned their rooms?",
        "Have you recently completed the report?",
        "Has he ever repaired a bicycle?",
        "Have we often organized team events?",
        "Have you already called the restaurant?",
        "Has she just posted the announcement?",
        "Have they ever volunteered at a shelter?",
        "Have you frequently attended these meetings?",
        "Has he recently updated his profile?",
        "Have we always tried to improve ourselves?",
        "Have you ever forgotten your passport?",
        "Has she already started writing the book?",
        "Have they always been interested in science?",
        "Have you just received the package?",
        "Has he ever performed on stage?",
        "Have we recently celebrated a big achievement?",
        "Have you ever cooked an exotic dish?",
        "Has she often given presentations at work?",
        "Have they already had lunch?",
        "Have you recently visited the doctor?",
        "Has he ever won a competition?",
        "Have we frequently gone on picnics together?",
        "Have you already completed your tasks?",
        "Has she ever painted a masterpiece?",
        "Have they just arrived at the party?",
        "Have you always loved traveling?",
        "Has he often told interesting stories?",
        "Have we recently met new clients?",
        "Have you ever planted a tree?",
        "Has she already prepared dinner?",
        "Have they frequently watched movies at the theater?",
        "Have you just returned from the trip?",
        "Has he ever written a poem?",
        "Have we always enjoyed working here?",
        "Have you often helped your siblings?",
        "Has she ever tried a new sport?",
        "Have they just organized the event?",
        "Have you already booked your vacation?",
        "Has he often shared his knowledge?",
        "Have we recently cleaned the garden?",
        "Have you ever designed your own clothes?",
        "Has she recently adopted a pet?",
        "Have they always supported each other?",
        "Have you just updated the database?",
        "Has he ever taught a class?",
        "Have we frequently had dinner together?",
        "Have you already finished reading the book?",
        "Has she ever played chess professionally?",
        "Have they recently attended a concert"
    };
    
    private Dictionary<string, HashSet<string>> wordCategories = new Dictionary<string, HashSet<string>>()
    {
        { "wh-word", new HashSet<string> { "why", "when", "where", "how", "what", "which" } },
        { "auxiliary", new HashSet<string> { "does", "do", "is", "are" } },
        { "subject", new HashSet<string> 
            { "she", "he", "it", "we", "they", "you", "john", "sarah", "david", "emma", "jack", "i",
            "John", "Sarah", "David", "Emma", "Tom", "Mike", "Lily", "Alice", "James", "Jack", "my parents", "the students",
            "her brother", "his father", "my friends", "the kids", "the birds", "the engineers", "the tourists", "my cousins",
            "my classmates", "my neighbors", "his cousin", "her sister", "the dogs", "his boss", "my grandparents", "the nurses",
            "the cat", "the baby", "who", "coffee", "car", "music", "emails", "ice cream", "movies", "homework", "office", "cat", "sushi", "cakes", "pictures", "glasses", "water", "bicycles", "computers", "tourists", "windows", "news", "bridges", "medicine",
            "she", "they", "he", "you", "it", "we", "John", "the students", "her brother", "my parents", "Sarah", "the kids", "your cat", "my neighbors", "his father", "my friends", "Emma", "the birds", "Alice", "Tom", "the workers", "her mother", "my cousins", "Jack", "the dogs", "his uncle", "my classmates", "Lily", "the tourists", "her boyfriend", "my teachers", "Mike", "the engineers", "his cousin",
            "she", "they", "he", "we", "you", "it", "John", "the students", "her brother", "my parents", "Sarah", "the kids", "your cat", "my neighbors", "his father", "my friends", "Emma", "the birds", "Alice", "Tom", "the workers", "her mother", "my cousins", "Jack", "the dogs", "his uncle", "my classmates", "Lily", "the tourists", "her boyfriend", "my teachers", "Mike", "the engineers", "his cousin",
            "she", "they", "he", "we", "you", "I", "her friends", "the guests", "their neighbors", "his desk", "her dog", "their room", "his house", "the train", "his bike", "the students", "the teacher", "their friends", "the birds", "the cats", "the furniture", "the jokes", "his scarf", "the jokes", "the hill",
            "she", "they", "he", "we", "you", "I", "her friends", "their neighbors", "his bike", "her desk", "their room", "the guests", "his house", "the cats", "the birds", "the teacher", "his client", "the students", "the car", "their friends", "the silverware", "the piano", "the couch", "her mother", "the manager", "the garden", "the meeting", "her book", "his scarf", "the hill", "their plans", "his partner", "her grandmother", "their project", "the package", "the new room", "the beach", "her dress", "the furniture", "his pencils", "the decorations", "the lost items", "the heavy boxes", "their dance routine", "the vase", "her favorite song", "her website", "the soup", "the trip", "the budget", "her future", "secrets",
            "you", "she", "they", "we", "he", "his parents", "your grandparents", "her friends", "the team", "the manager", "the director", "the guests", "the cats", "her siblings", "their neighbors", "the art gallery", "the application", "his teacher", "the house", "their relatives", "the doctor", "the party", "the museum", "the concert", "the office", "the birds", "his classmates", "the client", "the workshop", "her novel", "the marathon", "the garden", "the rules", "the report", "the package", "the professor", "the database", "the kitchen", "the library", "her book", "the house", "the furniture", "the living room", "the dishes", "their house", "the chair", "your passport", "your room", "his workspace", "the silverware", "the emails", "her pet", "her flight", "the software", "the piano", "the surprise party", "her portfolio", "the podcast", "the batteries"

        } },
        
        { "verb", new HashSet<string> 
            { "drink", "visit", "drive", "enjoy", "rain", "arrive", "play", "listen", "work", "call", "write", "like", "walk", "cook", "cost", "watch", "travel", "sleep", "have", "clean", "buy", "sell", 
            "exercise", "dance", "sing", "fix", "bake", "swim", "teach", "eat", "study", "read", "prefer", "sound", "help", "bark", "go", "ride", "repair", "send", "taste", "finish", "build", "wake",
            "is", "are", "am", "doing", "working", "thinking", "coming", "raining", "studying", "calling",
             "staying", "cooking", "going", "playing", "shouting", "waiting", "reading", "discussing",
             "having", "running", "barking", "arguing", "singing", "eating", "painting", "traveling",
             "meeting", "talking", "shopping", "helping", "learning", "swimming", "feeling", "crying",
             "watching", "walking", "sitting", "doing", "writing", "enjoying", "planning", "fixing",
             "taking", "practicing", "moving", "joining", "dancing", "cleaning", "becoming", "waiting",
             "designing", "searching", "washing", "speaking", "learning", "organizing", "starting",
             "visiting", "checking", "preparing", "standing", "trying", "building", "exploring",
             "enjoying", "feeding", "repairing", "making", "smiling", "forgetting", "opening",
             "calling", "driving", "recording", "solving", "sitting", "improving", "fixing", "holding",
             "delivering", "organizing", "working", "heading", "celebrating", "talking", "parking",
             "buying", "leaving", "discussing",
             "are", "is", "working", "coming", "laughing", "going", "thinking", "raining", "studying", "calling", "staying", "cooking", "playing", "shouting", "waiting", "reading", "watching", "discussing", "having", "running", "barking", "arguing", "singing", "eating", "painting", "traveling", "meeting", "snowing", "talking", "shopping", "helping", "learning", "swimming", "feeling", "crying", "planning", "fixing", "taking", "practicing", "moving", "joining", "dancing", "cleaning", "becoming", "waiting", "designing", "searching", "washing", "speaking", "learning", "organizing", "starting", "visiting", "checking", "preparing", "standing", "trying", "building", "exploring", "enjoying", "feeding", "repairing", "getting", "making", "smiling", "forgetting", "opening", "driving", "recording", "solving", "sitting", "improving", "playing", "fixing", "holding", "delivering", "organizing", "working", "heading", "celebrating", "talking", "parking", "buying", "leaving",
              "does", "drink", "do", "visit", "drive", "enjoy", "rain", "arrive", "play", "listen", "work", "call", "write", "love", "walk", "cook", "cost", "watch", "travel", "do", "sleep", "complain", "clean", "buy", "sell", "work", "exercise", "dance", "start", "fix", "love", "bake", "enjoy", "swim", "watch", "play", "smell", "take", "paint", "arrive", "call", "visit", "eat", "study", "read", "prefer", "sound", "sleep", "help", "bark", "work", "like", "go", "ride", "repair", "send", "taste", "finish", "play", "visit", "buy", "give", "open", "order", "watch", "wear", "rain", "dance", "play", "build", "study", "wake", "do", "visit", "drink", "go", "play", "forget", "sing", "write", "speak", "read", "work", "call", "visit", "study", "arrive", "meet", "live", "work", "play", "stay", "go", "like", "understand", "agree", "finish", "miss", "exercise", "arrive", "practice", "wake",
             "does", "did", "drink", "arrive", "play", "visit", "walk", "forget", "call", "help", "study", "travel", "work", "love", "clean", "sell", "cook", "rain", "cost", "watch", "dance", "fix", "exercise", "write", "speak", "buy", "bake", "learn", "listen", "paint", "meet", "sleep", "smell", "take", "sound", "read", "prefer", "agree", "give", "order", "open", "wear", "finish", "build", "wake", "prepare", "repair", "find", "lose", "return", "organize", "accept", "explain", "recommend", "celebrate", "answer", "complete", "borrow", "miss", "solve", "check", "teach", "prepare",
            "was", "were", "helping", "playing", "walking", "working", "cooking", "traveling", "trying", "reading", "planning", "speaking", "analyzing", "solving", "attending", "speaking", "completing", "waiting", "dancing", "thinking", "studying", "calling", "driving", "cleaning", "preparing", "checking", "organizing", "cooking", "watching", "explaining", "listening", "painting", "running", "behaving", "waiting", "playing", "eating", "fixing", "smiling", "enjoying", "taking", "singing", "shopping", "drawing", "helping", "making", "studying", "performing", "feeding", "repairing", "decorating", "reviewing", "solving", "discussing", "delivering", "teaching", "visiting", "sitting", "swimming", "preparing", "baking", "exploring", "decorating", "dusting", "solving", "climbing", "answering", "searching", "learning", "carrying", "planting", "arranging", "calculating",
            "will", "help", "play", "walk", "work", "cook", "travel", "try", "read", "plan", "speak", "analyze", "solve", "attend", "complete", "wait", "dance", "write", "improve", "think", "study", "call", "drive", "clean", "prepare", "check", "organize", "paint", "run", "behave", "fix", "smile", "enjoy", "take", "sing", "shop", "draw", "help", "make", "perform", "feed", "repair", "decorate", "review", "explore", "finish", "look", "discuss", "deliver", "teach", "sit", "swim", "prepare", "bake", "search", "listen", "watch", "talk", "ride", "cry", "head", "exercise", "paint", "hold", "iron", "sweep", "read", "design", "plant", "solve", "brush", "carry", "practice", "arrange", "learn", "try", "wait", "edit", "taste", "answer", "attend", "write", "whisper", "relax", "dust", "laugh", "wipe", "sew", "dream", "knit", "polish", "calculate", "climb",
            "have", "has", "traveled", "finished", "lived", "completed", "played", "visited", "solved", "gone", "eaten", "joined", "worked", "written", "started", "missed", "helped", "spoken", "sung", "arrived", "enjoyed", "practiced", "prepared", "admired", "moved", "been", "checked", "painted", "believed", "called", "discussed", "participated", "read", "submitted", "forgotten", "received", "performed", "celebrated", "cooked", "given", "met", "won", "watched", "cleaned", "planted", "told", "shared", "designed", "adopted", "tried", "booked", "organized", "explored", "reviewed", "returned", "tried", "uploaded", "respected", "aimed", "taken", "launched", "learned", "thought", "borrowed", "decorated", "recorded", "replaced", "appreciated", "installed", "grown", "competed", "removed"

        } },
        { "preposition", new HashSet<string> { "in", "on", "at", "to", "with", "for", "before", "after", "during", "as" } },
        { "averbs", new HashSet<string> { "always", "sometimes", "often", "rarely", "never", "usually", "hardly ever", "occasionally", "quickly", "quietly", "eagerly", "easily", "regularly", "slowly", "happily", "frequently", "seldom", "boldly", "carefully" } },
        { "time", new HashSet<string> { "morning", "weekends", "evening", "night", "winter", "Fridays" } }
    };

    void Start()
    {
        Debug.LogWarning("Show a Panel in which you say that atm no all words are recognized!");
        // in base al primo dropdown fai gli update
        HandlePhraseType();
        checkButton.onClick.AddListener(() => CheckUserInput(userInputField.text, selectedTense));
    }
    public void UpdateSelectedTense()
    {
        checkButton.onClick.RemoveAllListeners();
        checkButton.onClick.AddListener(() => CheckUserInput(userInputField.text, tenseDropdown.options[tenseDropdown.value].text));
        UpdateQuestionRule();
        Debug.Log("Selected Tense: " + tenseDropdown.options[tenseDropdown.value].text);
    }
    public void CheckUserInput(string userInput, string tense)
    {
        switch (phraseTypeDropdown.options[phraseTypeDropdown.value].text)
        {
            case "Questions":
                bool isValid = MatchesPresentSimpleQuestionsStructure(userInput);
                feedbackText.text = isValid ? "Correct!" : "Incorrect structure Or some words not yet recognized, please try another";
                break;
            case "Affirmations":
                break;
            case "Negations":
                break;
            default: Debug.Log("error on HandlePhraseType"); break;
        }
    }
    public void UpdateQuestionRule()
    {
        switch (tenseDropdown.options[tenseDropdown.value].text)
        {
            case "Present Simple": rule_dynamic_text.text = Return_PresentSimple_Question_Rules(); break; // spostare in un panel
            case "Past Simple": rule_dynamic_text.text = Return_Past_Simple_Question_Rules();  break;
            case "Present Continuous": rule_dynamic_text.text = Return_PresentContinuous_Question_Rules(); break;
            case "Past Continuous": rule_dynamic_text.text = Return_Past_Continuous_Question_Rule(); break;
            case "Future Simple": rule_dynamic_text.text = Return_Future_Simple_Question_Rule(); break;
            case "Present Perfect": rule_dynamic_text.text = Return_Present_Perfect_Question_Rule(); break;
            default: Debug.Log("error on UpdateQuestionRule"); break;
        }
        Debug.Log("Selected Tense: " + tenseDropdown.options[tenseDropdown.value].text);
    }
    public void UpdateAffirmationRule()
    {
        switch (tenseDropdown.options[tenseDropdown.value].text)
        {
            case "Present Simple": rule_dynamic_text.text = "{subject} {verb} {object}."; break;
            case "Past Simple": rule_dynamic_text.text = "{subject} {verb-past} {object}."; break;
            case "Present Continuous": rule_dynamic_text.text = "{subject} is/are {verb-ing} {object}."; break;
            case "Past Continuous": rule_dynamic_text.text = "{subject} was/were {verb-ing} {object}."; break;
            case "Future Simple": rule_dynamic_text.text = "{subject} will {verb} {object}."; break;
            case "Present Perfect": rule_dynamic_text.text = "{subject} have/has {verb-past} {object}."; break;
            default: Debug.Log("error on UpdateAffirmationRule"); break;
        }
        Debug.Log("Selected Tense: " + tenseDropdown.options[tenseDropdown.value].text);
    }
    public void UpdateNegationRule()
    {
        switch (tenseDropdown.options[tenseDropdown.value].text)
        {
            case "Present Simple": rule_dynamic_text.text = "{subject} do/does not {verb} {object}."; break;
            case "Past Simple": rule_dynamic_text.text = "{subject} did not {verb} {object}."; break;
            case "Present Continuous": rule_dynamic_text.text = "{subject} is/are not {verb-ing} {object}."; break;
            case "Past Continuous": rule_dynamic_text.text = "{subject} was/were not {verb-ing} {object}."; break;
            case "Future Simple": rule_dynamic_text.text = "{subject} will not {verb} {object}."; break;
            case "Present Perfect": rule_dynamic_text.text = "{subject} have/has not {verb-past} {object}."; break;
            default: Debug.Log("error on UpdateNegationRule"); break;
        }
        Debug.Log("Selected Tense: " + tenseDropdown.options[tenseDropdown.value].text);
    }
    public void HandlePhraseType()
    {
        switch (phraseTypeDropdown.options[phraseTypeDropdown.value].text)
        {
            case "Questions":
                UpdateQuestionRule(); break;
            case "Affirmations":
                UpdateAffirmationRule(); break;
            case "Negations":
                UpdateNegationRule(); break;
                default : Debug.Log("error on HandlePhraseType"); break;
        }
        Debug.Log("Selected Phrase Type: " + phraseTypeDropdown.options[phraseTypeDropdown.value].text);
    }
    private bool MatchesPresentSimpleQuestionsStructure(string input)
    {
        if ("Questions".Equals(phraseTypeDropdown.options[phraseTypeDropdown.value].text))
        {
            return ReturnQuestionsBasedOntense(input);
        }
        else if ("Affirmations".Equals(phraseTypeDropdown.options[phraseTypeDropdown.value].text))
        {
            return false;
        }
        else if ("Negations".Equals(phraseTypeDropdown.options[phraseTypeDropdown.value].text))
        {
            return true;
        }

        Debug.Log("The phrase is incorrect.");
        return false;
    }
    public void CloseRememberPanel()
    {
        rememberPanel.SetActive(false);
    }
    public bool ReturnQuestionsBasedOntense(string input)
    {
        switch (tenseDropdown.options[tenseDropdown.value].text)
        {
            case "Present Simple": return IsAValidSimpleQuestion(input, present_simple_questions);
            case "Past Simple": return IsAValidSimpleQuestion(input, past_simple_questions);
            case "Present Continuous": return IsAValidSimpleQuestion(input, present_continuous_questions);
            case "Past Continuous": return IsAValidSimpleQuestion(input, past_continuous_questions);
            case "Future Simple": return IsAValidSimpleQuestion(input, future_simple_questions);
            case "Present Perfect": return IsAValidSimpleQuestion(input, present_perfect_questions);
            default: Debug.Log("error on UpdateNegationRule"); return false;
        }
    }

    static bool IsAValidSimpleQuestion(string input, HashSet<string> possibleQuestions)
    {
        return possibleQuestions.Contains(input) ? true : false;
    }


    #region FILL QUESTIONS RULES
    private string Return_PresentSimple_Question_Rules()
    {
        return "1.(auxiliary) + (subject) + (frequency adverb) + (base verb) + (object) + (other adverbs)?" + "\nEx.Does she often visit her grandparents?\n\n" +
               "2.(wh- word/How) + (frequency adverb) + (auxiliary) + (subject) + (base verb) + (object) + (other adverbs)?" + "\nHow often do you visit your parents?";
    }
    private string Return_PresentContinuous_Question_Rules()
    {
        return "1.(Wh- word}/(How) + (auxiliary verb (am/are/is)} + (subject} + (frequency adverb) + (base verb + -ing) + (other adverbs)" + "\nEx.What are you doing?\n\n" +
               "2.How (auxiliary) + (subject) + (verb) + (complement)." + "\nHow is she working today?"; 
    }
    private string Return_Past_Simple_Question_Rules()
    {
        return "1.(Wh- word/How) + (did) + (subject) + (base verb) + (object/complement)?" + "\nWhat did you do yesterday?\n\n" +
               "2.(Wh- word) + (auxiliary) + (subject) + (base verb) + (complement)?" + "\nWhy did he leave early?";
    }
    private string Return_Past_Continuous_Question_Rule()
    {
        return "1.(Wh- word/How) + (was/were} + {subject} + {base verb + -ing} + {object/complement}?" + "\nWhat were you doing yesterday evening?\n\n" +
               "2.(auxiliary) + (subject) + (base verb + -ing) + (complement)" + "\nWas he sleeping at that time?";
    }
    private string Return_Future_Simple_Question_Rule()
    {
        return "1.(Wh- word/How) + (will) + (subject) + (base verb) + (object/complement)?" + "\nWhat will you do tomorrow?\n\n" +
               "2.Will + (subject) + (base verb) + (complement)." + "\nWill she come to the meeting?";
    }
    private string Return_Present_Perfect_Question_Rule()
    {
        return "1.(Wh- word/How) + (have/has) + (subject) + (past participle) + (object/complement)?" + "\nWhat have you done today?\n\n";
    }
    #endregion
}